### ISSUE TITLE
Bug with sending the title of the song that is currently playing

### ISSUE THREAD

**Issue by YarikAssShot** [SashaGoncharov19/shiva-bot#7]
If you do not restart the bot for a long time, then over time or with different commands, it will make the next bug
![image](https://user-images.githubusercontent.com/98362241/171909585-5995d43c-68ff-457f-ab3e-74a015751332.png)

**Comment by SashaGoncharov19** [comment]
Fixed in 3c15fa6b4f97a26d8aec9826130e8ec1cde29de3.
Closed.
